name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 16

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build and Deploy React App
        working-directory: react-test
        run: |
          cd react-test
          npm install
          npm run build
          # Add deployment commands if applicable (e.g., deploy to hosting service)

      - name: Build and Deploy Flask Backend
        working-directory: RecruitAppBackend
        run: |
          cd RecruitAppBackend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Add any additional setup or deployment commands

      - name: Deploy to Azure (if applicable)
        working-directory: RecruitAppBackend
        run: |
          # Add Azure deployment commands here
